name: Deploy Infrastructure

on:
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

jobs:
  terraform:
    if: ${{ github.event_name != 'pull_request_review' || github.event.review.state == 'approved' }}
    name: Deploy S3 Bucket
    uses: vcb-do-brasil/github-workflows/.github/workflows/terraform-infra-deploy.yml@main
    with:
      aws_region: ${{ vars.AWS_REGION }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}